In [2]:
import pandas as pd
 
df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv")
 
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:
def dataset_info(dataframe: pd.DataFrame) -> dict:
    return {
        "rows": dataframe.shape[0],
        "columns": dataframe.shape[1],
        "column_names": list(dataframe.columns)
    }
dataset_info(df)

{'rows': 150,
 'columns': 5,
 'column_names': ['sepal_length',
  'sepal_width',
  'petal_length',
  'petal_width',
  'species']}

In [4]:
df.loc[0, "petal_width"] = ""

In [10]:
def remove_invalid_rows(dataframe: pd.DataFrame) -> pd.DataFrame:
    valid_indices = filter(lambda idx: dataframe.loc[idx, "petal_width"] != "", dataframe.index)
    cleaned_df = dataframe.loc[list(valid_indices)].reset_index(drop=True)
    return cleaned_df

clean_df = remove_invalid_rows(df)
clean_df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [6]:
def normalize_species(dataframe: pd.DataFrame) -> pd.DataFrame:
    df_copy = dataframe.copy()
    df_copy["species"] = df_copy["species"].map(lambda x: x.strip().title())
    return df_copy

normalized_df = normalize_species(clean_df)
normalized_df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           4.9          3.0           1.4          0.2  Setosa
1           4.7          3.2           1.3          0.2  Setosa
2           4.6          3.1           1.5          0.2  Setosa
3           5.0          3.6           1.4          0.2  Setosa
4           5.4          3.9           1.7          0.4  Setosa

In [7]:
length_list_fp = list(
    map(lambda x: x * 3, filter(lambda x: x > 5.0, df["sepal_length"]))
)

length_list_fp[:5]

[15.299999999999999, 16.200000000000003, 16.200000000000003, 17.4, 17.1]

In [11]:
grouped_avg = normalized_df.groupby("petal_width")["sepal_length"].mean().to_dict()
grouped_avg

{0.1: 4.82,
 0.2: 4.9678571428571425,
 0.3: 4.971428571428571,
 0.4: 5.3,
 0.5: 5.1,
 0.6: 5.0,
 1.0: 5.414285714285714,
 1.1: 5.3999999999999995,
 1.2: 5.779999999999999,
 1.3: 5.884615384615385,
 1.4: 6.325,
 1.5: 6.183333333333334,
 1.6: 6.375,
 1.7: 5.800000000000001,
 1.8: 6.3999999999999995,
 1.9: 6.34,
 2.0: 6.6499999999999995,
 2.1: 6.916666666666667,
 2.2: 6.866666666666667,
 2.3: 6.9125000000000005,
 2.4: 6.266666666666667,
 2.5: 6.733333333333333}